export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_REFRESH = 'AUTH_REFRESH';

export const LOG_OUT = 'LOG_OUT';


export const COMPLAIN_START = 'COMPLAIN_START';
export const COMPLAIN_SUCCESS = 'COMPLAIN_SUCCESS';
export const COMPLAIN_FAIL = 'COMPLAIN_FAIL';
export const COMPLAIN_REFRESH = 'COMPLAIN_REFRESH';

export const GET_USER_PROFILE_START = 'GET_USER_PROFILE_START';
export const GET_USER_PROFILE_SUCCESS = 'GET_USER_PROFILE_SUCCESS';
export const GET_USER_PROFILE_FAIL = 'GET_USER_PROFILE_FAIL';
export const GET_USER_PROFILE_REFRESH = 'GET_USER_PROFILE_REFRESH';

export const AMEND_USER_PROFILE_START = 'AMEND_USER_PROFILE_START';
export const AMEND_USER_PROFILE_SUCCESS = 'AMEND_USER_PROFILE_SUCCESS';
export const AMEND_USER_PROFILE_FAIL = 'AMEND_USER_PROFILE_FAIL';
export const AMEND_USER_PROFILE_REFRESH = 'AMEND_USER_PROFILE_REFRESH';


export const GET_USER_COMPLAINT_START = 'GET_USER_COMPLAINT_START';
export const GET_USER_COMPLAINT_SUCCESS = 'GET_USER_COMPLAINT_SUCCESS';
export const GET_USER_COMPLAINT_FAIL = 'GET_USER_COMPLAINT_FAIL';
export const GET_USER_COMPLAINT_REFRESH = 'GET_USER_COMPLAINT_REFRESH';


export const CREATE_ACCOUNT_START = 'CREATE_ACCOUNT_START';
export const CREATE_ACCOUNT_SUCCESS = 'CREATE_ACCOUNT_SUCCESS';
export const CREATE_ACCOUNT_FAIL = 'CREATE_ACCOUNT_FAIL';
export const CREATE_ACCOUNT_REFRESH = 'CREATE_ACCOUNT_REFRESH';

export const GET_HISTORY_START = 'GET_HISTORY_START';
export const GET_HISTORY_SUCCESS = 'GET_HISTORY_SUCCESS';
export const GET_HISTORY_FAIL = 'GET_HISTORY_FAIL';


export const GET_COMMENT_START = 'GET_COMMENT_START';
export const GET_COMMENT_SUCCESS = 'GET_COMMENT_SUCCESS';
export const GET_COMMENT_FAIL = 'GET_COMMENT_FAIL';


export const SEND_COMMENT_START = 'SEND_COMMENT_START';
export const SEND_COMMENT_SUCCESS = 'SEND_COMMENT_SUCCESS';
export const SEND_COMMENT_FAIL = 'SEND_COMMENT_FAIL';
export const SEND_COMMENT_REFRESH = 'SEND_COMMENT_REFRESH';

export const DELETE_COMMENT_START = 'DELETE_COMMENT_START';
export const DELETE_COMMENT_SUCCESS = 'DELETE_COMMENT_SUCCESS';
export const DELETE_COMMENT_FAIL = 'DELETE_COMMENT_FAIL';
export const DELETE_COMMENT_REFRESH = 'DELETE_COMMENT_REFRESH';

export const DELETE_EMAIL_START = 'DELETE_EMAIL_START';
export const DELETE_EMAIL_SUCCESS = 'DELETE_EMAIL_SUCCESS';
export const DELETE_EMAIL_FAIL = 'DELETE_EMAIL_FAIL';
export const DELETE_EMAIL_REFRESH = 'DELETE_EMAIL_REFRESH';


export const GET_COURSES_START = 'GET_COURSES_START';
export const GET_COURSES_SUCCESS = 'GET_COURSES_SUCCESS';
export const GET_COURSES_FAIL = 'GET_COURSES_FAIL';
export const GET_COURSES_REFRESH = 'GET_COURSES_REFRESH'; 


export const ADD_COURSES_START = 'ADD_COURSES_START';
export const ADD_COURSES_SUCCESS = 'ADD_COURSES_SUCCESS';
export const ADD_COURSES_FAIL = 'ADD_COURSES_FAIL';
export const ADD_COURSES_REFRESH = 'ADD_COURSES_REFRESH'; 

export const POST_EXAMINER_START = 'POST_EXAMINER_START';
export const POST_EXAMINER_SUCCESS = 'POST_EXAMINER_SUCCESS';
export const POST_EXAMINER_FAIL = 'POST_EXAMINER_FAIL';
export const POST_EXAMINER_REFRESH = 'POST_EXAMINER_REFRESH';

export const EXAMINER_TO_STUDENT_START = 'EXAMINER_TO_STUDENT_START';
export const EXAMINER_TO_STUDENT_SUCCESS = 'EXAMINER_TO_STUDENT_SUCCESS';
export const EXAMINER_TO_STUDENT_FAIL = 'EXAMINER_TO_STUDENT_FAIL';
export const EXAMINER_TO_STUDENT_REFRESH = 'EXAMINER_TO_STUDENT_REFRESH';


export const GET_EXAMINER_START = 'GET_EXAMINER_START';
export const GET_EXAMINER_SUCCESS = 'GET_EXAMINER_SUCCESS';
export const GET_EXAMINER_FAIL = 'GET_EXAMINER_FAIL';
export const GET_EXAMINER_REFRESH = 'GET_EXAMINER_REFRESH';


export const POST_STUDENT_START = 'POST_STUDENT_START';
export const POST_STUDENT_SUCCESS = 'POST_STUDENT_SUCCESS';
export const POST_STUDENT_FAIL = 'POST_STUDENT_FAIL';
export const POST_STUDENT_REFRESH = 'POST_STUDENT_REFRESH';


export const POST_LECTURER_START = 'POST_LECTURER_START';
export const POST_LECTURER_SUCCESS = 'POST_LECTURER_SUCCESS';
export const POST_LECTURER_FAIL = 'POST_LECTURER_FAIL';
export const POST_LECTURER_REFRESH = 'POST_LECTURER_REFRESH';



export const STUDENT_TO_EXAMINER_START = 'STUDENT_TO_EXAMINER_START';
export const STUDENT_TO_EXAMINER_SUCCESS = 'STUDENT_TO_EXAMINER_SUCCESS';
export const STUDENT_TO_EXAMINER_FAIL = 'STUDENT_TO_EXAMINER_FAIL';
export const STUDENT_TO_EXAMINER_REFRESH = 'STUDENT_TO_EXAMINER_REFRESH';

export const STUDENT_TO_LECTURER_START = 'STUDENT_TO_LECTURER_START';
export const STUDENT_TO_LECTURER_SUCCESS = 'STUDENT_TO_LECTURER_SUCCESS';
export const STUDENT_TO_LECTURER_FAIL = 'STUDENT_TO_LECTURER_FAIL';
export const STUDENT_TO_LECTURER_REFRESH = 'STUDENT_TO_LECTURER_REFRESH';

export const GET_STUDENT_MAILS_START = 'GET_STUDENT_MAILS_START';
export const GET_STUDENT_MAILS_SUCCESS = 'GET_STUDENT_MAILS_SUCCESS';
export const GET_STUDENT_MAILS_FAIL = 'GET_STUDENT_MAILS_FAIL';
export const GET_STUDENT_MAILS_REFRESH = 'GET_STUDENT_MAILS_REFRESH';